import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import AppProvider from '@/components/app-provider';
import { ToastContainer } from 'react-toastify';
import NextTopLoader from 'nextjs-toploader';
import Script from 'next/script';

export const metadata: Metadata = {
  title: `B'Restaurant`,
  description: 'Generated by create next app',
};

const manropo = Manrope({ subsets: ['latin'], variable: '--font-manrope' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/vanta/0.5.24/vanta.globe.min.js"
          strategy="afterInteractive"
        />
      </head>
      <body className={manropo.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader showSpinner={false} color="hsl(var(--foreground))" />
          <AppProvider>
            <main>{children}</main>
            <ToastContainer
              hideProgressBar={true}
              autoClose={3000}
              theme="light"
            />
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
