import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import AppProvider from '@/components/app-provider';
import { ToastContainer } from 'react-toastify';
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: 'Udecademy',
  description: 'Generated by create next app',
};

const manropo = Manrope({ subsets: ['latin'], variable: '--font-manrope' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={manropo.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <div className="wrapper grid grid-cols-[300px,minmax(0,1fr)] h-screen">
            <Sidebar></Sidebar> */}

          <NextTopLoader showSpinner={false} color="hsl(var(--foreground))" />
          <AppProvider>
            <main>{children}</main>
            <ToastContainer hideProgressBar={true} autoClose={1000} />
          </AppProvider>
        </ThemeProvider>
        {/* </div> */}
      </body>
    </html>
  );
}
